### ISSUE TITLE
IWidgetBodyContent does not support plain ReactNode content

### ISSUE THREAD

**Issue by Partovic** [OfficeDev/microsoft-teams-ui-component-library#101]
### Reproduction

Currently it doesn't seem to be possible to use plain ReactNodes as content. It is only allowed to render charts or text placeholders. Is that intended to be correct?

### Expected Behavior

TWidgetContent should have a third type e.g. "Generic" which allows us to set a ReactNode as content property value.

### Actual Behavior

Only charts or text placeholders can be rendered.

**Comment by thure** [comment]
This is by design. We hear you, though, and we're working on a redesign of the API that permits this over at [`fluent-react-patterns`](https://github.com/OfficeDev/fluent-react-patterns).
