### ISSUE TITLE
Teams-UI-Kit: brand color

### ISSUE THREAD

**Issue by MajorBoo** [OfficeDev/microsoft-teams-ui-component-library#102]
Hi friends, 
I am currently learning Teams-UI-Kit and ran into a problem, I could not find information on how to properly generate a brand color color scheme like this:
![Capture2](https://user-images.githubusercontent.com/93913816/145192347-13838094-bb73-412f-8822-c9c364eeb684.PNG)

If anyone could explain it would help me a lot.
Thanks!

**Comment by thure** [comment]
Using your own brand colors is not currently facilitated by this project.
