### ISSUE TITLE
Left Nav / Side Bar Component

### ISSUE THREAD

**Issue by APhanSpAARC** [OfficeDev/microsoft-teams-ui-component-library#103]
Hi All,

One important UI component which seems to be missing from this library is the left navigation bar. I'd like to propose this component be added to the component library so that Teams app can have a uniform way of implementing this. 

![image](https://user-images.githubusercontent.com/79124479/145754043-5a615a02-060a-4768-a5d7-ec6f0a63c659.png)

**Comment by thure** [comment]
If you can offer a design that uses this pattern in an app you’re planning for Teams, I can try to build consensus around this idea.
