### ISSUE TITLE
Upgrade Northstar dependency

### ISSUE THREAD

**Issue by thure** [OfficeDev/microsoft-teams-ui-component-library#116]
This should include handling the change in `@fluentui/react-icons` which removed inherent dimensions from SVGs. It's causing some confusion: #80, #115.

Let's fix that.

[Codesandbox](https://codesandbox.io/s/fluentui-react-teams-issue-template-forked-0ms31h?file=/package.json)

**Comment by AndrewCraswell** [comment]
Shouldn't northstar be a peer dependency, rather than a direct dependency?

**Comment by ilyassloudrassi** [comment]
+, I hope it will be solved soon.

**Comment by thure** [comment]
@ilyassloudrassi, this is an excellent first issue. If you derive value from this package, we’d welcome a PR that resolves this :)

**Comment by ilyassloudrassi** [comment]
Unfortunately the update solved only the icons in the list component, in Wizard icons for completing the step still not showing + the steps stopped functioning activeStepIndex doesn't make any impact on the UI.

**Comment by ilyassloudrassi** [comment]
Unfortunately the update solved only the icons in the list component, in Wizard icons for completing the steps still not showing + Checkbox selectivity doesn't show up on List rows.

**Comment by thure** [comment]
What specific version of the alpha exhibited those issues? We bumped the version a few times today, and I'm not seeing any regressions with icons as of [6.0.0-alpha.18](https://www.npmjs.com/package/@fluentui/react-teams/v/6.0.0-alpha.18).

If you're using that version and still seeing issues, could you provide a CodeSandbox so we can investigate?

**Comment by thure** [comment]
Closing this, as actually any follow-up should be in a new issue regarding the specific problem given no further upgrade to Northstar is applicable.

@ilyassloudrassi if you are observing issues in [6.0.0-alpha.18](https://www.npmjs.com/package/@fluentui/react-teams/v/6.0.0-alpha.18), please file a new issue with the CodeSandbox. Thanks!
