### ISSUE TITLE
Failed to parse source map from. 

### ISSUE THREAD

**Issue by StanDEV1234340t98** [OfficeDev/microsoft-teams-ui-component-library#117]
i've created a react project with the following command 

npx create-react-app contact-center
And i'm using the react-teams package, but i'm getting this error; for multiple files.

![Untitled](https://user-images.githubusercontent.com/98811905/158999642-8904aaad-10e0-45e1-910f-aef52704448f.png)

i'm using "@fluentui/react-teams": "5.3.0", but version 6.0.0 will give me the same error.

WARNING in ./node_modules/@fluentui/react-teams/lib/esm/types/types.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Documents\react\contact-center\node_modules\@fluentui\react-teams\src\types\types.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Documents\react\contact-center\node_modules\@fluentui\react-teams\src\types\types.ts'

looks like i'm missing the src folder. Do you know what i'm doing wrong?

Ah I think it's because i'm referencing a ts file from a js file, is there a way to make this work?

**Comment by thure** [comment]
You shouldn't need the `src` folder, this package exports `cjs` and `ejs` packages that are already transpiled.

I'm not sure what could be going on here, but if you need to use the TypeScript sources for this project, you'll definitely want to set up TypeScript in your project.
