### ISSUE TITLE
Playground: Broken link/XML

### ISSUE THREAD

**Issue by DJStompZone** [OfficeDev/microsoft-teams-ui-component-library#129]
### Reproduction

Click the "Playground" link on the front page of the repo, or follow one of the following links:
https://dev-int.teams.microsoft.com/storybook/main/
https://dev.teams.microsoft.com/storybook/main/index.html

Note, the playground does seem to be accessible, the [link on Microsoft Docs](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates) is working, but this exact behavior is also exhibited if the user clicks the logo at the top left of that page:
![react-library-logo-v2](https://user-images.githubusercontent.com/85457381/167273602-4000d94d-f0e8-4b95-8099-7c4135352c15.jpg)
<https://dev-int.teams.microsoft.com/storybook/main/>

### Expected Behavior

Playground opens to a valid website, ideally the correct one. (Namely, [this one](https://dev-int.teams.microsoft.com/storybook/main/index.html))

### Actual Behavior

The following error is shown exclusively.
```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.

<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:3931694f-201e-0007-735f-62773a000000 Time:2022-05-07T22:14:45.9468040Z</Message>
</Error>
```

**Comment by thure** [comment]
It was taken down for security reasons, apologies for the inconvenience. It'll be back soon.

**Comment by thure** [comment]
This is now definitely resolved: https://dev.teams.microsoft.com/storybook/main/index.html
