### ISSUE TITLE
Link to Playground broken

### ISSUE THREAD

**Issue by marcus-castro-sp** [OfficeDev/microsoft-teams-ui-component-library#136]
Hi there,

The link for the Playground on the README file seems to be incorrect. It's redirecting me to: "https://dev.teams.microsoft.com/storybook/main/index.html", which gives the following error message:

![image](https://user-images.githubusercontent.com/65231173/169349175-506e7d10-bf29-4d5b-a322-308df508ee29.png)

![image](https://user-images.githubusercontent.com/65231173/169348987-3d8e64e5-3e23-4761-9f1f-1e3617742adb.png)

**Comment by thure** [comment]
It was taken down for security reasons, apologies for the inconvenience. It'll be back soon.

**Comment by thure** [comment]
This is a duplicate of #129.

**Comment by thure** [comment]
This and its duplicate are now resolved :)
