### ISSUE TITLE
Forms and Pickers don't seem to be working

### ISSUE THREAD

**Issue by BrendanAndrade** [OfficeDev/microsoft-teams-ui-component-library#46]
Documentation says there should be picker and form components: 
https://dev-int.teams.microsoft.com/storybook/main/index.html?path=/story/ui-templates-forms--kitchen-sink
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-basic-ui-components#picker
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/design/design-teams-app-ui-templates#form

Are these not available in the SDK? If so, it should probably be noted in the documentation.

If they are available, could you post a quick example?

Much thanks!

**Comment by thure** [comment]
Hi @BrendanAndrade, apologies for the delay.

The `Form` component doesn’t yet implement the picker designs you linked, though that may come in a future release. It does implement single- and multi-select dropdowns with simple string options. The example for Form available in the “Playground” linked in the Readme demonstrates all the types of input Form currently supports.

Essentially this library implements most of the UI Templates designs seen in the Microsoft Teams UI Kit in Figma's Community: https://www.figma.com/community/file/916836509871353159/Microsoft-Teams-UI-Kit
