### ISSUE TITLE
Boards: Add and Edit Textbox not working properly

### ISSUE THREAD

**Issue by craduran** [OfficeDev/microsoft-teams-ui-component-library#49]
The Title and Subtitle Textbox keeps onblur after typing a character when you try to add an item on the boards.

**Comment by davezuko** [comment]
Hey @craduran, sorry about that. I just took a peek and found the problem in the Form component used by Boards. I've opened up a PR with a fix.

**Comment by davezuko** [comment]
A temporary fix has been merged. I'll have to ask the project about their release process to get this published.

**Comment by craduran** [comment]
thanks, it's working now.
