### ISSUE TITLE
Current package ships only ES6 module format, consider including Common-JS as well

### ISSUE THREAD

**Issue by drub0y** [OfficeDev/microsoft-teams-ui-component-library#56]
This package currently only ships a `/lib/index.js` that is in the ES6 module format (e.g. using language keywords like `export`). This is fine for browsers, but it creates an issue for unit testing in Jest especially out of the box using `create-react-app --typescript` which I think could be fairly argued is the way that the majority of React developers are using to bootstrap their new projects these days.

All the other `@fluentui/react-xxx` libs ship with multiple module support by shipping both `commonjs` and `es` in the box under `dist` and then using `files`, `main` and `module` in their `package.json` definitions to guide importers to the correct ones. This then provides the best overall experience for the developer who might be using a toolchain that requires one or the other.

I would like to suggest this library follow suit and _at least_ build and ship common-js and es modules in the package.

**Comment by drub0y** [comment]
A workaround for now, for those of you using `create-react-app` as your starting point, is to add the following to your `package.json` to configure Jest to not transform this library's files:

```JSON
"jest": {
  "transformIgnorePatterns": [
    ".+/\\@fluentui/react-teams/.+\\.js$"
  ]
}
```

**Comment by davezuko** [comment]
Sounds reasonable to me. I can take a look at our build scripts when I get a spare cycle.
