### ISSUE TITLE
The icons are not showing 

### ISSUE THREAD

**Issue by BesnikMahmuti-Prosperoware** [OfficeDev/microsoft-teams-ui-component-library#59]
![image](https://user-images.githubusercontent.com/52067178/108535929-1f64bf80-72dc-11eb-8903-2a7b0e698399.png)

![image](https://user-images.githubusercontent.com/52067178/108535979-31466280-72dc-11eb-8f0a-33c4b4df874f.png)

I'm using the list grid and the icons are not showing for me.

I'm also using the latest packages mentioned in the GitHub MD description.

**Comment by LeandroMendesDS** [comment]
I'm having the same issue! Did you solve it? Can you please explain it to me?
