### ISSUE TITLE
Hideable columns are revealed too soon

### ISSUE THREAD

**Issue by thure** [OfficeDev/microsoft-teams-ui-component-library#6]
There appears to be a 20px window where a hideable column is displayed before there is room to display it.

<img width="257" alt="94185895-cee75400-fe5a-11ea-901c-fa3fd6c252c9" src="https://user-images.githubusercontent.com/855039/94867930-02942200-03f7-11eb-8678-30de35a59a69.png">

**Comment by pret-a-porter** [comment]
@thure https://github.com/OfficeDev/microsoft-teams-ui-component-library/pull/8 I have tried to solve this problem
