### ISSUE TITLE
Support avatars and icons alongside text content in Table

### ISSUE THREAD

**Issue by BesnikMahmuti-Prosperoware** [OfficeDev/microsoft-teams-ui-component-library#66]
Is there a way to include inside a grid cell the icon and text.

**Comment by thure** [comment]
@BesnikMahmuti-Prosperoware, can you provide details on the specific use-case or design you’re trying to achieve?

When you say 'grid', which component are you referring to?

**Comment by BesnikMahmuti-Prosperoware** [comment]
By grid, I mean table component. Something like this example but instead of avatars I would like to be able to show icons.
![image](https://user-images.githubusercontent.com/52067178/110473927-5f4ee380-80df-11eb-993c-494f783d2e48.png)

**Comment by thure** [comment]
@BesnikMahmuti-Prosperoware sorry for the long delay — at this time we haven't built support even for the avatars, and I'll need to check with the designers of this library on whether the pattern you describe can be supported.

Support for all Fluent UI icons is just now making it to this library: #69.
