### ISSUE TITLE
is Wizard component work correctly 

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/microsoft-teams-ui-component-library#70]
I tried to use wizard component but it didn't work ?

is there any sample for that ?

**Comment by thure** [comment]
Hi @asith-w — you can see a functioning example of the Wizard in [this library's Storybook](https://dev-int.teams.microsoft.com/storybook/main/index.html?path=/story/ui-templates-wizard--kitchen-sink-in-base-surface).

The code for this component is in [the corresponding Storybook story](https://github.com/OfficeDev/microsoft-teams-ui-component-library/blob/main/stories/Wizard.stories.tsx).

You can see documentation about Wizard's props in [the API docs for `IWizardProps`](https://github.com/OfficeDev/microsoft-teams-ui-component-library/blob/main/docs/react-teams.iwizardprops.md).

I hope this helps! Let us know if you have any additional questions.
