### ISSUE TITLE
Icons are not visible

### ISSUE THREAD

**Issue by plamber** [OfficeDev/microsoft-teams-ui-component-library#80]
Hello,
I am integrating the library in a new react project. Unfortunately, I am not able to see the Icons associated to the components. This issue is related with  #59. 

### Reproduction
I am using these packages:
![image](https://user-images.githubusercontent.com/18241305/120146635-ab448c80-c1e5-11eb-8366-35047b88198e.png)

The results looks like this
![image](https://user-images.githubusercontent.com/18241305/120146682-c0b9b680-c1e5-11eb-814c-3699a6a307b7.png)

```
import React, { Component, Suspense } from 'react';
import { Route, Switch, NavLink, useHistory } from "react-router-dom";
import { useEffect, useState } from "react";
import * as microsoftTeams from "@microsoft/teams-js";
import { Provider } from "@fluentui/react-teams";
import { themeNames } from "@fluentui/react-teams";
import ChildComponent from "./components/ChildComponent"

const initTeamsTheme = (theme: string | undefined) : themeNames => {
  switch (theme) {
    case "dark":
      return themeNames.Dark;
    case "contrast":
      return themeNames.HighContrast;
    default:
      return themeNames.Default;
  }
}

function App() {
  const [appContext, setAppContext] = useState<microsoftTeams.Context>();
  const [appAppearance, setAppAppearance] = useState<themeNames>(
    themeNames.Default
  );

  useEffect(() => {
    microsoftTeams.getContext((context) => {
      setAppContext(context);
      setAppAppearance(initTeamsTheme(context.theme));

      microsoftTeams.appInitialization.notifySuccess();
    });

    microsoftTeams.registerOnThemeChangeHandler((theme) => {
      setAppAppearance(initTeamsTheme(theme));
    });
  }, []);

  return (
    <Provider themeName={appAppearance} lang="en-US">
      <Switch>
        <Route exact path="/" component={MyStuff} />
      </Switch>
    </Provider>
  );
}

/*
class App extends Component<{}, {
  appContext?: microsoftTeams.Context,
  appAppearance: themeNames
}> {
  constructor(props: any) {
    super(props);
    this.state = {
      appAppearance: themeNames.Default,
    };
  }

  componentDidMount = (): void => {
    microsoftTeams.getContext((context) => {
      this.setState({
        appContext: context,
        appAppearance: initTeamsTheme(context.theme)
      });
      microsoftTeams.appInitialization.notifySuccess();
    });

    microsoftTeams.registerOnThemeChangeHandler((theme) => {
      this.setState({
        appAppearance: initTeamsTheme(theme)
      })
    });
  };

  render() {
    const { appAppearance } = this.state;
    return (
      <Provider themeName={appAppearance} lang="en-US">
          <Switch>
              <Route path={["/"]} exact component={MyStuff} />  
              <Route path={["/create"]} exact component={() => <React.Fragment>Wizard</React.Fragment>} />
              <Route component={() => <React.Fragment>NotFound</React.Fragment>} />
          </Switch>
      </Provider>
    );
  }
}
*/

export default App;
```

```
import React from 'react';
import { Toolbar } from '@fluentui/react-teams';

const ChildComponent: React.FunctionComponent = () => {
    const toolbarConfig = {
        actionGroups: {},
        filters: [
          {
            id: "i1",
            title: "Edible flowers",
            items: [
              { id: "i1i1", title: "Dianthus" },
              { id: "i1i2", title: "Mentha" },
              { id: "i1i3", title: "Passiflora" },
            ],
          },
          { id: "i2", title: "Podded vegetables" },
        ],
        filtersSingleSelect: true,
        find: true,
      };
  return (
    <React.Fragment>
        <Toolbar {...toolbarConfig}   />
    </React.Fragment>
  )
};

export default ChildComponent;
```

Not sure if I am missing a reference or some initialization. I was not able to find the steps in the documentation or the sample project.

Thank you for your help,
Patrick

**Comment by thure** [comment]
Hi @plamber — when you inspect the icons, is the markup for the icons present? If so, what are the computed styles of the individual elements of the SVG?

**Comment by thure** [comment]
Hi @plamber — we (the react-teams developers) haven't observed this issue before and aren't able to reproduce it with the code you're sharing… I suspect it has something to do with the way your stack is set up.

Could you please reproduce this on a CodeSandbox or similar and share the link, or share a repository with the code you're using that shows the same bug?

Also, for what it's worth, these components are only tested in Chrome/Chromium since this is meant only for Teams apps, so things may not work in Firefox/Gecko or other UA's / layout engines. We are also currently on v0.54 of react-northstar and react-northstar-icons, though personally I don't suspect that is the issue.

**Comment by plamber** [comment]
Hi @thure,
thank you for your input and help. 

I created a react app npx create-react-app using typescript. You can find [here](https://github.com/plamber/teamsplayground) a simple repository with the issue.

I added these dependencies:
- npm i react-router-dom
- npm i --save-dev @types/react-router-dom
- npm i @microsoft/teams-js
- npm i @fluentui/react-northstar
- npm i --save @fluentui/react-teams

You can run it with npm start and it should automatically redirect you to a browser using http://localhost:3000/. 

The result in Edge and Chrome is this:
![image](https://user-images.githubusercontent.com/18241305/120740084-ce778080-c4f2-11eb-86de-20b265e74109.png)

Regarding the comment of browser support. We are trying to build an application that can exist in Teams, SharePoint Online, but also in a browser only. The application should have the "Microsoft ecosystem" feeling when working in any of these locations. Our thought was to use the fluent-ui to achieve this goal. 
What I am hearing from your comment is that this can't be achieved with this library at all. What are your recommendations for building applications that can "live in multiple" places but keep the Microsoft feel when accessing them?

Thank you for your help and feedback.

**Comment by thure** [comment]
Hi @plamber — Installing the dependencies as listed in the this repo's package.json them gives the following warnings:

```
warning " > @fluentui/react-northstar@0.54.0" has incorrect peer dependency "react@^16.8.0".
warning " > @fluentui/react-northstar@0.54.0" has incorrect peer dependency "react-dom@^16.8.0".
…[and many similar warnings]
```

These are meaningful warnings, since `@fluentui/react-northstar` won't render things correctly without the right version of React. Icons render correctly and the warnings go away by setting `react` and `react-dom` dependencies to ^16.8.0.

Regarding browser support, I believe `@fluentui/react-northstar` aims to be fairly universal though it's true it doesn't implement the Teams UI Kit as this library does. We'd welcome issues or PR's if you find bugs in Firefox or others.

**Comment by plamber** [comment]
Thank you for the feedback. Missed this dependency part

Will give it a try. 

Cheers

**Comment by thure** [comment]
I'll mark this as closed for now in that case, please feel free to reopen it if icons are still not visible after setting compatible dependencies! Certainly feel free to open new issues if you see problems in other UA's like Firefox.

**Comment by plamber** [comment]
Hi,
I tested it out. Had to downgrade the packages of my react 17 project to:

```
"@types/react": "^16.8.0",
"@types/react-dom": "^16.8.0",
"react": "^16.8.0",
"react-dom": "^16.8.0",
```

Afterwards, everything started showing up correctly in all browsers.

Thank you
