### ISSUE TITLE
Need deployment guide to host in azure

### ISSUE THREAD

**Issue by loksayi** [OfficeDev/microsoft-teams-ui-component-library#81]
Hi team,
Can anyone help me out here to deploy the app and host it in Azure?
Do we have any supporting documentation or guide on how can we deploy it to Azure and make it work as a playground version?

**Comment by thure** [comment]
Hi @loksayi — there is a guide for this in the getting started docs: [Build and run your first Microsoft Teams app with React](https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?tabs=vscode#deploy-your-app-to-azure).

**Comment by loksayi** [comment]
Hi Thure,
Thanks for responding. But I'm unable to deploy the app through visual studio code. I'm getting the attached error when I'm following the steps as per Microsoft docs. 

FYI : This app is having Story book as well in the project.
![image](https://user-images.githubusercontent.com/39863754/121059579-3ffb4b80-c7df-11eb-883b-663c1a5fb32f.png)

**Comment by loksayi** [comment]
> Hi Thure,
> Thanks for responding. But I'm still unable to provison/deploy the app through visual studio code. I'm getting the attached error when I'm following the steps as per Microsoft docs.
> 
> FYI : This app is having Story book as well in the project.
> 
> Question : Do we need to use pipelines for deploying these kind of apps ? or any other way to host/deploy it ? Kindly suggest
> 
> ![image](https://user-images.githubusercontent.com/39863754/121059579-3ffb4b80-c7df-11eb-883b-663c1a5fb32f.png)

@thure

**Comment by asnow003** [comment]
Hello @loksayi have you tried our Visual Studio Code extension... it will guide you through deploying to Azure and can get more support there if you have issues.  

Go to VS Code and install the extension by searching for "Teams toolkit"

**Comment by loksayi** [comment]
Hi @asnow003,
First of all thanks for responding. The errors that I have mentioned above are from the VS code Teams Toolkit extension only. It was not supporting this project type to deploy it to azure. Do we have any other options to do it?

**Comment by loksayi** [comment]
Thanks for the replies guys.
I got the solution by building the storybook using **_yarn run build-storybook_** which gives a static website in output folder name storybook-static. Then I have referred to the following link for deploying a static website to azure blob storage which got worked.
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-static-website-how-to?tabs=azure-portal
