### ISSUE TITLE
Cannot read property 'siteVariables' of undefined

### ISSUE THREAD

**Issue by SallahuLeonita** [OfficeDev/microsoft-teams-ui-component-library#85]
### Reproduction
I've imported { Table, themeNames, Provider as TeamsProvider } from @fluentui/react-teams and I'm getting the below error:
Cannot read property 'siteVariables' of undefined

![image](https://user-images.githubusercontent.com/52403968/122183278-5d897e80-ce8b-11eb-9dc9-b80c0bfc07da.png)

![image](https://user-images.githubusercontent.com/52403968/122183316-68441380-ce8b-11eb-824e-a68febfbea53.png)

**Comment by SallahuLeonita** [comment]
Hi, is there any update on this issue?

**Comment by thure** [comment]
Hi @SallahuLeonita, apologies for the delay. I'm not able to reproduce the issue as you describe it, could you please show the code where the provider is rendered?
